# Grafana Datasource Provisioning

apiVersion: 1

datasources:
  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "10s"
      httpMethod: POST

  # TimescaleDB for blockchain data
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: blueblocks_indexer
    user: blueblocks
    secureJsonData:
      password: ${TESTNET_DB_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
    editable: false
